#!/bin/sh
#
# ------------------------------------------------------
#
# cpo_code build script for M0 coprocessor
#
# GNU assembler/binutils version 2.22
# Fedora Linux 3.4.4-4.fc16.x86_64
#
# ------------------------------------------------------
# Example:
# ------------------------------------------------------
#
# 	./build_cpo_code cpo_uart	 // usart3 -> M0 -> scheme
# 	./build_cpo_code cpo_usb	 // usb1 -> M0 -> scheme
#
# ------------------------------------------------------

arm-none-eabi-as -o a.o $1.s
arm-none-eabi-ld -Map $1.map -Ttext 0x00 -o a.elf a.o
arm-none-eabi-objcopy -O binary a.elf  $1.bin
rm a.o
rm a.elf

